library("randomForest")
setwd("data")
train <- read.csv("train.csv")
test <- read.csv("test.csv")
fit <- randomForest(as.factor(hand) ~ S1 + C1 + S2 + C2 + S3 + C3 + S4 + C4 + S5 + C5, data=train, importance=TRUE, ntree=2000)
varImpPlot(fit)
Prediction <- predict(fit, test)
submit <- data.frame(id = test$id, hand = Prediction)
write.csv(submit, file = "rforest.csv", row.names = FALSE)
